name: Minify JavaScript

on:
  push:
    branches: [ main, master ]
    paths:
      - 'vimeo-ott-datalayer.js'
  pull_request:
    paths:
      - 'vimeo-ott-datalayer.js'
  workflow_dispatch:  # Allows manual triggering

# Add this permissions block to grant write access
permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install terser --no-save
        
      - name: Minify JavaScript
        run: npx terser vimeo-ott-datalayer.js --compress --mangle --output vimeo-ott-datalayer.min.js
        
      - name: Add file size comments
        run: |
          ORIGINAL_SIZE=$(wc -c < vimeo-ott-datalayer.js)
          MINIFIED_SIZE=$(wc -c < vimeo-ott-datalayer.min.js)
          SAVINGS=$(echo "scale=2; (($ORIGINAL_SIZE-$MINIFIED_SIZE)/$ORIGINAL_SIZE)*100" | bc)
          echo "/* Original: ${ORIGINAL_SIZE} bytes, Minified: ${MINIFIED_SIZE} bytes, Saved: ${SAVINGS}% */" > temp.js
          cat vimeo-ott-datalayer.min.js >> temp.js
          mv temp.js vimeo-ott-datalayer.min.js
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add vimeo-ott-datalayer.min.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "Minify vimeo-ott-datalayer.js [automated]" && git push)